Perspective correction
cs-23-sw-6-21/WhiteboardApp pull request #30
Opened 2023-03-10 13:45 UTC by Mati-AAU

2023-03-14 09:47 UTC, mads256h requested changes

2023-03-14 09:47 UTC, mads256h commented on app/src/main/java/dk/scuffed/whiteboardapp/pipeline/stages/GLOutputStage.kt.orig
> +package dk.scuffed.whiteboardapp.pipeline.stages
Delete this file

2023-03-14 09:47 UTC, mads256h commented on app/src/main/java/dk/scuffed/whiteboardapp/pipeline/stages/opengl_process_stages/PerspectiveCorrectionStage.kt
> +    }
Use the function in LineFloat

2023-03-14 09:47 UTC, mads256h commented on app/src/main/java/dk/scuffed/whiteboardapp/pipeline/stages/points_stages/PerspectiveTransformPointsStage.kt
> +        */
Remove these comments

2023-03-14 09:47 UTC, mads256h commented on app/src/main/java/dk/scuffed/whiteboardapp/pipeline/stages/points_stages/PerspectiveTransformPointsStage.kt
> +
Free all your mats here

2023-03-16 10:22 UTC, Mati-AAU commented on app/src/main/java/dk/scuffed/whiteboardapp/pipeline/stages/opengl_process_stages/PerspectiveCorrectionStage.kt
> +    }
done

2023-03-16 10:24 UTC, Mati-AAU commented on app/src/main/java/dk/scuffed/whiteboardapp/pipeline/stages/points_stages/PerspectiveTransformPointsStage.kt
> +
done

2023-03-16 11:47 UTC, Mati-AAU commented on app/src/main/java/dk/scuffed/whiteboardapp/pipeline/stages/GLOutputStage.kt.orig
> +package dk.scuffed.whiteboardapp.pipeline.stages
done

2023-03-16 12:04 UTC, S3JER requested changes
Only some places need docs, else LGTM

2023-03-16 12:04 UTC, S3JER commented on app/src/main/java/dk/scuffed/whiteboardapp/pipeline/stages/points_stages/PerspectiveTransformPointsStage.kt
> +        val warpmat = Imgproc.getPerspectiveTransform(src, dst)
Maybe a new name to warpmat

2023-03-16 12:08 UTC, S3JER approved these changes
LGTM

2023-03-16 12:10 UTC, S3JER approved these changes

2023-03-16 12:28 UTC, merged