White balancing
cs-23-sw-6-21/WhiteboardApp pull request #66
Opened 2023-04-04 13:17 UTC by Mati-AAU

2023-04-12 09:32 UTC, Casper-NS requested changes
Minor changes needed but otherwise lgtm.

2023-04-12 09:32 UTC, Casper-NS commented on app/src/main/java/dk/scuffed/whiteboardapp/pipeline/stage_combinations/FullPipeline.kt
> +    )
Figure out how it binarization plays together with whitebalancing before merge

2023-04-12 09:32 UTC, Casper-NS commented on app/src/main/java/dk/scuffed/whiteboardapp/pipeline/stages/opengl_process_stages/WhitebalanceStage.kt
> +    private val inputFramebufferInfo1: FramebufferInfo,
Potentential for better naming of framebuffers

2023-04-12 09:32 UTC, Casper-NS commented on app/src/main/res/raw/saturate_shader.glsl
> +*/
We dont like commented code, either add or remove it

2023-04-12 09:32 UTC, Casper-NS commented on app/src/main/res/raw/whitebalance_shader.glsl
> +uniform sampler2D framebuffer1;
Rename to better explain what is what in terms of actual picture and whitebalancing

2023-04-14 07:55 UTC, Casper-NS commented on app/src/main/java/dk/scuffed/whiteboardapp/pipeline/stage_combinations/FullPipeline.kt
> +    )
works

2023-04-14 08:00 UTC, Casper-NS commented on app/src/main/java/dk/scuffed/whiteboardapp/pipeline/stages/opengl_process_stages/WhitebalanceStage.kt
> +    private val inputFramebufferInfo1: FramebufferInfo,
updated

2023-04-14 08:01 UTC, Casper-NS commented on app/src/main/res/raw/saturate_shader.glsl
> +*/
removed

2023-04-14 08:13 UTC, Casper-NS approved these changes

2023-04-14 08:19 UTC, S3JER approved these changes

2023-04-14 08:20 UTC, merged